[package]
name = "viv_script"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
inkwell_llvm12 = "0.1.2"
nom = "7.1.1"
nom_locate = "4.0.0"
